---
title: "Reproducible Research   Course Project 2"
author: "John Lin"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Synopsis

## Data Processing

```{r, message = FALSE}
# Load libraries.
library(plyr)
library(dplyr)
library(reshape)
library(ggplot2)
library(gridExtra)
library(egg)
```

```{r, cache = TRUE}
# Download data.
if (!file.exists("data.csv.bz2")) {
  download.file(url = "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2", 
                destfile = "data.csv.bz2")
}

# Load data.
data <- read.csv("data.csv.bz2")
```

https://github.com/flyingdisc/RepData_PeerAssessment2/blob/master/how-to-handle-PROPDMGEXP.md

```{r}
# Calculate number of fatalities or injuries.
event.by.fatal.injur <- data %>% 
  group_by(EVTYPE) %>% 
  summarize(fatalities = sum(FATALITIES, na.rm = TRUE),
            injuries = sum(INJURIES, na.rm = TRUE))
event.by.fatal.injur$both <- with(event.by.fatal.injur, fatalities + injuries)
```

```{r}
# Replace CROPDMGEXP and PROPDMGEXP.
exp.to.mult <- function(x) {
  levels(x)[1] <- "Blank"
  revalue(x, c("H" = 100, "h" = 100, "K" = 1000, "k" = 1000, "M" = 1000000,
          "m" = 1000000, "B" = 1000000000, "b" = 1000000000,
          "+" = 1, "-" = 0, "?" = 0, "Blank" = 0, " " = 0, 
          "0" = 10, "1" = 10, "2" = 10, "3" = 10, "4" = 10, 
          "5" = 10, "6" = 10, "7" = 10, "8" = 10, "9" = 10))
}
data$damage.crop <- as.numeric(data$CROPDMG) *
  as.numeric(exp.to.mult(data$CROPDMGEXP)) 
data$damage.prop <- as.numeric(data$PROPDMG) *
  as.numeric(exp.to.mult(data$PROPDMGEXP))

# Calculate actual damage in USD.
event.by.damage <- data %>%
  group_by(EVTYPE) %>%
  summarize(crop = sum(damage.crop, na.rm = TRUE),
            prop = sum(damage.prop, na.rm = TRUE))
event.by.damage$both <- with(event.by.damage, crop + prop)
```

## Results
```{r}
# Plot.
p1 <- ggplot(arrange(event.by.fatal.injur, desc(fatalities))[1:5, c(1,2)],
             aes(reorder(EVTYPE, -fatalities), fatalities)) +
  geom_col() + ggtitle("Fatalities") + xlab("") + ylab("") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p2 <- ggplot(arrange(event.by.fatal.injur, desc(injuries))[1:5, c(1,3)],
             aes(reorder(EVTYPE, -injuries), injuries)) +
  geom_col() + ggtitle("Injuries") + xlab("") + ylab("") +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p3 <- ggplot(arrange(event.by.fatal.injur, desc(both))[1:5, c(1,4)],
             aes(reorder(EVTYPE, -both), both)) +
  geom_col() + ggtitle("Combined") + xlab("") + ylab("") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggarrange(p1, p2, p3, nrow = 1, 
          top = "Top 5 event types by fatalities and/or injuries",
          left = "Frequency", bottom = "Event type")
```

```{r}
# Plot.
p4 <- ggplot(arrange(event.by.damage, desc(crop))[1:5, c(1,2)],
             aes(reorder(EVTYPE, -crop), crop)) +
  geom_col() + ggtitle("Crop") + xlab("") + ylab("") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p5 <- ggplot(arrange(event.by.damage, desc(prop))[1:5, c(1,3)],
             aes(reorder(EVTYPE, -prop), prop)) +
  geom_col() + ggtitle("Property") + xlab("") + ylab("") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
p6 <- ggplot(arrange(event.by.damage, desc(both))[1:5, c(1,4)],
             aes(reorder(EVTYPE, -both), both)) +
  geom_col() + ggtitle("Combined") + xlab("") + ylab("") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggarrange(p4, p5, p6, nrow = 1, 
          top = "Top 5 event types by crop and/or property damage",
          left = "Damage (USD)", bottom = "Event type")
```
